Feature: Cognito auth (#8)
* Add Cognito auth

* Enable CORS

* Updates to frontend to use Cognito auth

* Updates to backend to use Cognito auth

* Add lint step to frontend build

* Add caching for npm packages in GitHub workflow

* Add an HttpApi

* Remove cors headers from lambda response

* Pass CloudFromation outputs to frontend build

* Add AdminUser

* Add README

* Got authorizer finally working with by lowercasing `issuer` and `audience` in JwtConfig. Found the resolution in GitHub issue here: https://github.com/aws/aws-sam-cli/issues/2410

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,20 +21,24 @@ jobs:
       - name: Build backend
         working-directory: backend
         run: sam build
-      
+
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
+          # role-to-assume: ${{ secrets.PIPELINE_EXECUTION_ROLE }}
+          # role-session-name: dev-deployment
+          # role-duration-seconds: 3600
+          # role-skip-session-tagging: true
 
       - name: Package backend artifact
         working-directory: backend
         run: |
           sam package \
               --s3-bucket ${{ secrets.ARTIFACT_BUCKET }} \
-              > template.yaml       
+              > template.yaml
 
       - name: Upload backend artifact
         uses: actions/upload-artifact@v2
@@ -46,9 +50,22 @@ jobs:
       #
       # Build and package frontend
       #
+      - uses: actions/cache@v2
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
       # - name: Install frontend dependencies
       #   working-directory: frontend
       #   run: npm install
+
+      - name: Lint frontend
+        working-directory: frontend
+        run: |
+          npm install @vue/cli-service
+          npm run lint
 
       # - name: Build frontend
       #   working-directory: frontend
@@ -59,16 +76,18 @@ jobs:
         with:
           name: frontend-artifact
           # path: frontend/dist/
-          path: frontend/
+          path: |
+            frontend/
+            !frontend/node_modules/
           if-no-files-found: error
-  
+
   deploy-dev:
     if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
     name: Deploy to Dev
     needs: build
     environment: dev
     env:
-      ENV_NAME: dev
+      STACK_NAME: lottochecker-dev
     runs-on: ubuntu-latest
     steps:
       - name: Configure AWS Credentials
@@ -77,6 +96,10 @@ jobs:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ secrets.AWS_REGION }}
+          # role-to-assume: ${{ env.PIPELINE_EXECUTION_ROLE }}
+          # role-session-name: testing-deployment
+          # role-duration-seconds: 3600
+          # role-skip-session-tagging: true
 
       - name: Download backend artifact
         uses: actions/download-artifact@v2
@@ -85,9 +108,8 @@ jobs:
 
       - name: Deploy backend
         run: |
-          sam deploy --config-env development \
-              --stack-name "lottochecker-$ENV_NAME" \
-              --s3-bucket ${{ secrets.DEPLOY_ARTIFACT_BUCKET }} \
+          sam deploy --stack-name "$STACK_NAME" \
+              --s3-bucket ${{ secrets.ARTIFACT_BUCKET }} \
               --no-fail-on-empty-changeset \
               --no-confirm-changeset \
               --capabilities CAPABILITY_IAM \
@@ -100,13 +122,26 @@ jobs:
           # path: dist/
           path: frontend
 
+      - uses: actions/cache@v2
+        with:
+          path: ~/.npm
+          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-node-
+
       - name: Install frontend dependencies
         working-directory: frontend
         run: npm install
 
+      - name: Save CloudFormation outputs to file
+        working-directory: frontend
+        run: aws cloudformation describe-stacks --stack-name $STACK_NAME --query 'Stacks[0].Outputs[]' > cf_outputs.json
+
       - name: Build frontend for Dev
         env:
-          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}
+          VUE_APP_HOST: ${{ secrets.APP_HOST_URL }}
+          VUE_APP_OAUTH_REDIRECT_SIGNIN: ${{ secrets.APP_HOST_URL }}
+          VUE_APP_OAUTH_REDIRECT_SIGNOUT: ${{ secrets.APP_HOST_URL }}
           VUE_APP_FIREBASE_API_KEY: ${{ secrets.VUE_APP_FIREBASE_API_KEY }}
           VUE_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.VUE_APP_FIREBASE_AUTH_DOMAIN }}
           VUE_APP_FIREBASE_PROJECT_ID: ${{ secrets.VUE_APP_FIREBASE_PROJECT_ID }}
@@ -114,7 +149,25 @@ jobs:
           VUE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VUE_APP_FIREBASE_MESSAGING_SENDER_ID }}
           VUE_APP_FIREBASE_APP_ID: ${{ secrets.VUE_APP_FIREBASE_APP_ID }}
         working-directory: frontend
-        run: npm run build:frontend -- --dest ../dist --modern
+        run: |
+          echo "Parsing CloudFormation outputs to env vars..."
+          export VUE_APP_USER_POOL_ID=$(jq -r '.[] | select(.OutputKey=="UserPoolId") | .OutputValue' cf_outputs.json)
+          export VUE_APP_USER_POOL_WEB_CLIENT_ID=$(jq -r '.[] | select(.OutputKey=="UserPoolWebClientId") | .OutputValue' cf_outputs.json)
+          export VUE_APP_API_URL=$(jq -r '.[] | select(.OutputKey=="HttpApi") | .OutputValue' cf_outputs.json | sed 's/{state}/'tx'/g' | sed 's/{game}/TexasLotto/g')
+          export VUE_APP_AUTH_URL=$(jq -r '.[] | select(.OutputKey=="UserPoolAuthDomain") | .OutputValue' cf_outputs.json)
+          export VUE_APP_COGNITO_REGION=$(jq -r '.[] | select(.OutputKey=="CognitoRegion") | .OutputValue' cf_outputs.json)
+          # Make sure all required vars are set.
+          echo "VUE_APP_USER_POOL_ID: $VUE_APP_USER_POOL_ID"
+          echo "VUE_APP_USER_POOL_WEB_CLIENT_ID: $VUE_APP_USER_POOL_WEB_CLIENT_ID"
+          echo "VUE_APP_API_URL: $VUE_APP_API_URL"
+          echo "VUE_APP_AUTH_URL: $VUE_APP_AUTH_URL"
+          echo "VUE_APP_COGNITO_REGION: $VUE_APP_COGNITO_REGION"
+          # if [[ -z $VUE_APP_AWS_COGNITO_REGION || -z $VUE_APP_USER_POOL_ID || -z $VUE_APP_USER_POOL_WEB_CLIENT_ID || -z $VUE_APP_AUTH_URL || -z $VUE_APP_OAUTH_REDIRECT_SIGNIN || -z $VUE_APP_OAUTH_REDIRECT_SIGNOUT || -z $VUE_APP_API_URL ]]; then
+          #     echo "One or more required env variables is not defined."
+          #     exit 1
+          # fi
+          echo "Building frontend Vue app..."
+          npm run build:frontend -- --dest ../dist --modern
 
       - name: Deploy frontend
         run: |
